# This workflow will build and release a .NET project

name: Build & Release

# Run the workflow after changes in the "master" branch
on:
  push:
    branches: [ "master" ]

jobs:
  build_and_release:

    # Use "windows-2019" runner for .NET Framework 4.x projects and "windows-latest" for .NET Core projects
    runs-on: windows-2019

    # Define env variables containing project properties
    # Use TIMT (The-Infinite-Monkey-Theorem) prefix for variable names
    env:
      TIMT_PROJECT_NAME: 'Snaffler'
      TIMT_SOLUTION_FILE: 'Snaffler.sln'
      TIMT_BINARY_PATH: '${{ github.workspace }}\Snaffler\bin\Release'
      TIMT_BINARY_FILE: '${{ github.workspace }}\Snaffler\bin\Release\Snaffler.exe'

    steps:

    - name: SharpPack - Checkout Source Code
      uses: actions/checkout@v3
      with:
        repository: hasksomatotoian/SharpPack
        path: SharpPack
        ref: refs/heads/master
        token: ${{ secrets.REPO_ACCESS_KEY }}

    - name: SharpPack - Restore
      run: dotnet restore SharpPack/SharpPack.sln

    - name: SharpPack - Build
      run: dotnet build SharpPack/SharpPack.sln
