# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Install Pre-Requisities
      uses: NuGet/setup-nuget@v1.2.0, microsoft/setup-msbuild@v1.1
    - name: Restore
      run: nuget restore Snaffler.sln
    - name: Build
      run: msbuild Snaffler.sln -t:rebuild -property:Configuration=Release
