# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1.2.0
    - name: Restore
      run: nuget restore Snaffler.sln
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: msbuild Snaffler.sln -t:rebuild -property:Configuration=Release
    - name: Dir
      run: dir $GITHUB_WORKSPACE\bin\Release
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: PWD
      run: pwd
    - name: List
      run: ls -la
    - name: List
      run: ls $GITHUB_WORKSPACE -la
